[package]
name = "bodoConnect"
version = "0.1.0"
edition = "2021"

[dependencies]
subprocess = "0.2.9"
tokio = "1.27.0"
reachable = "0.2.2"
external-ip = "4.2.0"
futures = "0.3.27"
mac_address = { git = "https://github.com/topongo/mac_address" }
reqwest = "0.11.16"
clap = { version = "4.2.1", features = ["derive"] }
log = "0.4.17"
chrono = "0.4.24"
colored = "2.0.0"
lazy_static = "1.4.0"
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"