name: Build with Docker

on:
  push:
    # tags:
    #   - '*'
  workflow_dispatch:

jobs:
  build_docker_image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build using docker
      run: |
        docker run --rm -v .:/src -u root topongo/rust-android-openssl:latest cargo build --release
        ls target/release

        

  # build_android_bin:
  #   
    
